-- MySQL Script generated by MySQL Workbench
-- 06/04/15 17:15:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BlaBlaPaczka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BlaBlaPaczka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BlaBlaPaczka` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BlaBlaPaczka` ;

-- -----------------------------------------------------
-- Table `BlaBlaPaczka`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlaBlaPaczka`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `hashedPassword` VARCHAR(200) NOT NULL,
  `username` VARCHAR(200) NULL,
  `authenticationToken` VARCHAR(200) NOT NULL,
  `createdAt` DATE NOT NULL,
  `signInCount` INT NOT NULL DEFAULT 0,
  `currentLoginAt` DATE NOT NULL,
  `lastLoginAt` DATE NULL,
  `email` VARCHAR(100) NULL DEFAULT 'undefined',
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`phoneNumber` ASC),
  UNIQUE INDEX `AuthToken_UNIQUE` (`authenticationToken` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlaBlaPaczka`.`logEntries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlaBlaPaczka`.`logEntries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(200) NOT NULL,
  `entry` VARCHAR(200) NOT NULL,
  `createdAt` DATE NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `logEntry_User_idx` (`userId` ASC),
  CONSTRAINT `logEntry_User`
    FOREIGN KEY (`userId`)
    REFERENCES `BlaBlaPaczka`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
